KEK_Emlak.Web/Controllers/BuyController.cs
using KEK_Emlak.Data.Entities;
using KEK_Emlak.Service.Interface;
using KEK_Emlak.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KEK_Emlak.Web.Controllers
{
  
    public class BuyController : Controller
    {
        private IProductService productService;
        private UserManager<ApplicationUser> userManager;
        private SignInManager<ApplicationUser> signInManager;
        private IBuyService buyService;
        private ISellService sellService;

        public BuyController(IProductService productService, UserManager<ApplicationUser> userManager, 
            SignInManager<ApplicationUser> signInManager,
            ISellService sellService,
            IBuyService buyService)
        {
            this.productService = productService;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.buyService = buyService;
            this.sellService = sellService;
        }
        [HttpPost]
        [Authorize]
        public IActionResult BuyProduct(ProductVM product)
        {
            var user = GetCurrentUserAsync().Result;
            Buy buy = new Buy();
            buy.BuyerId = user.Id;
            buy.ProductId = product.Id;
            buy.Price = product.Price;
            Sell sell = new Sell();
            sell.SellerId = product.AddedBy;
            sell.ProductId = product.Id;
            sell.Price = product.Price;
            buyService.InsertBuy(buy);
            sellService.InsertSell(sell);
            return Redirect("/Buy/Emlak"); 
        }  
        [HttpGet]
        [Authorize]
        public IActionResult Emlak()
        {
            var user = GetCurrentUserAsync().Result;
            List<BuyVM> sells = new List<BuyVM>();
            var lst = buyService.GetBuys().Where(s => s.BuyerId == user.Id).ToList();
            foreach (var item in lst)
            {
                var product = productService.GetProducts().Where(s => s.Id == item.ProductId).FirstOrDefault();
                var name = product.Name;
                BuyVM sell = new BuyVM();
                sell.BuyId = item.Id;
                sell.ProductName = name;
                sell.Price = item.Price;
                sells.Add(sell);
            }
            return View(sells);
        }
          
        [HttpGet]
        [Authorize(Roles ="Admin")]
        public IActionResult AllBuys()
        {
            List<BuyVM> buys = new List<BuyVM>();
            var lst = buyService.GetBuys().ToList();
            foreach (var item in lst)
            {
                var product = productService.GetProducts().Where(s => s.Id == item.ProductId).FirstOrDefault();
                var name = product.Name;
                BuyVM sell = new BuyVM();
                sell.BuyId = item.Id;
                sell.ProductName = name;
                sell.Price = item.Price;
                buys.Add(sell);
            }
            return View(buys);
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => userManager.GetUserAsync(HttpContext.User);

    }
    public class BuyVM
    {
        public int BuyId { get; set; }
        public string ProductName { get; set; }
        public long Price { get; set; }

    }
}

KEK_Emlak.Web/Controllers/ProductController.cs
using KEK_Emlak.Data.Entities;
using KEK_Emlak.Service.Interface;
using KEK_Emlak.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KEK_Emlak.Web.Controllers
{
    public class ProductController : Controller
    {
        private IProductService productService;
        private ICategoryService categoryService;
        private IFileHandler fileHandler;
        private UserManager<ApplicationUser> userManager;
        private SignInManager<ApplicationUser> signInManager;
        private ISellService sellService;

        public ProductController(IProductService productService, ISellService sellService, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ICategoryService categoryService, IFileHandler fileHandler)
        {
            this.productService = productService;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.categoryService = categoryService;
            this.fileHandler = fileHandler;
            this.sellService = sellService;
        }
        [HttpGet]
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Index()
        {
           
                  var  products = productService.GetProducts();
               

            return View(products);
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> UserProduct()
        {
            var cUser = GetCurrentUserAsync().Result;
            IEnumerable<Product> products = new List<Product>();
            string userrole = string.Empty;
            if (cUser != null)
            {
                if (await userManager.IsInRoleAsync(cUser ,"Admin"))
                {
                    products = productService.GetProducts();
                }
                if (await userManager.IsInRoleAsync(cUser, "Seller"))
                {
                    products = productService.GetProducts().Where(s => s.AddedBy == cUser.Id);
                }
            }

            return View(products);
        }
        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.Cagetories = new SelectList(categoryService.GetCategorys().ToList(), "Id", "Name");
            return View();
        }
        
        [HttpGet]
        public IActionResult Details(int id)
        {
            ProductVM product = new ProductVM();
            string user = string.Empty;
            if (signInManager.IsSignedIn(User))
            {
                 user = GetCurrentUserAsync().Result.Id.ToString();
            }
            var prs = productService.GetProduct(id);
            product.Id = prs.Id;
            product.Name = prs.Name;
            product.Details = prs.Details;
            product.DisplayImage = prs.DisplayImage;
            product.Image2 = prs.Image2;
            product.Image3 = prs.Image3;
            product.Image5 = prs.Image5;
            product.Image4 = prs.Image4;
            product.Price = prs.Price;
            product.Area = prs.Area;
            product.Location = prs.Location;
            product.AddedBy = prs.AddedBy;
            product.canBuy = prs.AddedBy == user ? false : true;
            product.CategoryName =categoryService.GetCategory(prs.CategoryId).Name;
            return View(product);
        }

        [HttpPost]
        public IActionResult Create(ProductVM model)
        {
            string displayImage = null;
            string Image1 = null;
            string image2 = null;
            string image3 = null;
            string image4 = null;
            Product product = new Product();
            if (model.DisplayImageFile != null)
            {
                 displayImage = fileHandler.UploadFile("Product", model.DisplayImageFile);
            }
            if (model.Image2File != null)
            {
                 Image1 = fileHandler.UploadFile("Product", model.Image2File);
            }
            if (model.Image3File != null)
            {
                 image2 = fileHandler.UploadFile("Product", model.Image3File);
            }
            if (model.Image4File != null)
            {
                 image3 = fileHandler.UploadFile("Product", model.Image4File);
            }
            if (model.Image5File != null) 
            { 
                 image4 = fileHandler.UploadFile("Product", model.Image5File); 
            }
            product.Name = model.Name;
            product.Details = model.Details;
            product.DisplayImage = displayImage;
            product.Image2 = Image1;
            product.Image3 = image2;
            product.Image4 = image3;
            product.Image5 = image4;
            product.Price = model.Price;
            product.Area = model.Area;
            product.Location = model.Location;
            product.CategoryId = model.CategoryId;
            product.AddedBy = GetCurrentUserAsync().Result.Id;
            productService.InsertProduct(product);
            return RedirectToAction(nameof(UserProduct));
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Cagetories = new SelectList(categoryService.GetCategorys().ToList(), "Id", "Name");
            var model = productService.GetProduct(id);
            ProductVM product = new ProductVM();
            product.Name = model.Name;
            product.Details = model.Details;
            product.DisplayImage = model.DisplayImage;
            product.Image2 = model.Image2;
            product.Image3 = model.Image3;
            product.Image4 = model.Image4;
            product.Image5 = model.Image5;
            product.Price = model.Price;
            product.Area = model.Area;
            product.Location = model.Location;
            product.CategoryId = model.CategoryId;
            return View(product);
        }

        [HttpPost]
        public IActionResult Update(ProductVM model)
        {
            string displayImage = null;
            string Image1 = null;
            string image2 = null;
            string image3 = null;
            string image4 = null;
            Product product = new Product();
            if (model.DisplayImageFile != null)
            {
                displayImage = fileHandler.UpdateFile(model.DisplayImage, "Product", model.DisplayImageFile);
                product.DisplayImage = displayImage;
            }
            else
            {
                product.DisplayImage = model.DisplayImage; ;
            }
            if (model.Image2File != null)
            {
                Image1 = fileHandler.UpdateFile(model.Image2,"Product", model.Image2File);
                product.Image2 = Image1;
            }
            else
            {
                product.Image2 = model.Image2; ;
            }
            if (model.Image3File != null)
            {
                image2 = fileHandler.UpdateFile(model.Image3,"Product", model.Image3File);
                product.Image3 = image2;
            }
            else
            {
                product.Image3 = model.Image3; ;
            }
            if (model.Image4File != null)
            {
                image3 = fileHandler.UpdateFile(model.Image4, "Product", model.Image4File);
                product.Image4 = image3;
            }
            else
            {
                product.Image4 = model.Image4; ;
            }
            if (model.Image5File != null)
            {
                image4 = fileHandler.UpdateFile(model.Image5, "Product", model.Image5File);
                product.Image5 = image4;
            }
            else
            {
                product.Image5 = model.Image5; ;
            }
            product.Id = model.Id;
            product.Name = model.Name;
            product.Details = model.Details;
            product.Price = model.Price;
            product.Area = model.Area;
            product.Location = model.Location;
            product.CategoryId = model.CategoryId;
            product.AddedBy = GetCurrentUserAsync().Result.Id;
            productService.UpdateProduct(product);
            return RedirectToAction(nameof(UserProduct));
        }


        [HttpGet]
        public IActionResult Delete(int id)
        {
            var model = productService.GetProduct(id);
            return View(model);
        }
        [HttpPost]
        public IActionResult DeleteConfirm(Product product)
        {
            productService.DeleteProduct(product.Id);
            return RedirectToAction(nameof(UserProduct));
        }



        [HttpGet]
        [Authorize]
        public IActionResult Sells()
        {
            var user = GetCurrentUserAsync().Result;
            List<SellVM> sells = new List<SellVM>();
            var lst = sellService.GetSells().Where(s=>s.SellerId==user.Id).ToList();
            foreach (var item in lst)
            {
                var product = productService.GetProducts().Where(s => s.Id == item.ProductId).FirstOrDefault();
                var name = product.Name;
                SellVM sell = new SellVM();
                sell.SellId = item.Id;
                sell.ProductName = name;
                sell.Price = item.Price;
                sells.Add(sell);
            }
            return View(sells);
        }
        [HttpGet]
        [Authorize]
        public IActionResult AllSells()
        {
            List<SellVM> sells = new List<SellVM>();
            var lst = sellService.GetSells().ToList();
            foreach(var item in lst)
            {
                var product = productService.GetProducts().Where(s => s.Id == item.ProductId).FirstOrDefault();
                var name = product.Name;
                SellVM sell = new SellVM();
                sell.SellId = item.Id;

KEK_Emlak.Web/Views/Product/AllSells.cshtml
@model IEnumerable<KEK_Emlak.Web.Controllers.SellVM>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<section class="wrapper">
    <h3><i class="fa fa-angle-right"></i> Satış Listesi</h3>

    <div class="row mt">
        <div class="col-md-12">
            <div class="content-panel">
                <table class="table table-striped table-advance table-hover">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="pull-left"> <h4><i class="fa fa-angle-right"></i>Tüm Ürünler</h4></div>
                        </div>
                    </div>

                    <hr>
                    <thead>
                        <tr>
                            <th hidden>#</th>
                            <th>İsim</th>
                            <th>Fiyat</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td hidden>@item.SellId</td>
                                <td>@item.ProductName</td>
                                <td>@item.Price</td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
            <!-- /content-panel -->
        </div>
        <!-- /col-md-12 -->
    </div>
</section>

KEK_Emlak.Web/Views/Product/Create.cshtml
@model KEK_Emlak.Web.Models.ProductVM

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<section class="wrapper">
    <h3><i class="fa fa-angle-right"></i>Satış Yap</h3>

    <div class="form-panel">
        <h4 class="mb"><i class="fa fa-angle-right"></i>Emlak Oluştur</h4>
        <form class="form-horizontal style-form" method="post" asp-action="Create" asp-controller="Product" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="col-sm-2 col-sm-2 control-label">İsim</label>
                        <div class="col-sm-10">
                            <input type="text" asp-for="Name" required class="form-control round-form" placeholder="Ürün Başlığı">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 col-sm-2 control-label">Kategori</label>
                        <div class="col-sm-10">
                            @Html.DropDownList("CategoryId", (SelectList)ViewBag.Cagetories, "Kategori seçiniz", new { @class = "form-control round-form", @required = "Select City" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 col-sm-2 control-label">Detaylar</label>
                        <div class="col-sm-10">
                            <textarea required type="text" asp-for="Details" class="form-control round-form" placeholder="Emlak Detayları"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 col-sm-2 control-label">Fiyat</label>
                        <div class="col-sm-10">
                            <input required type="number" asp-for="Price" class="form-control round-form" placeholder="Fiyat giriniz">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 col-sm-2 control-label">Alan</label>
                        <div class="col-sm-10">
                            <input required type="number" asp-for="Area" class="form-control round-form" placeholder="Metrekare cinsinden giriniz">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 col-sm-2 control-label">Adres</label>
                        <div class="col-sm-10">
                            <input type="text" asp-for="Location" class="form-control round-form" placeholder="Lütfen adres Belirtiniz">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="col-sm-2 col-sm-2 control-label">Asıl Resim</label>
                        <div class="col-sm-10">
                            <input type="file" asp-for="DisplayImageFile" class="fileinput-button">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 col-sm-2 control-label">Emlak fotoğraf</label>
                        <div class="col-sm-10">
                            <input type="file" asp-for="Image2File" class="fileinput-button">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 col-sm-2 control-label">Emlak fotoğraf</label>
                        <div class="col-sm-10">
                            <input type="file" asp-for="Image3File" class="fileinput-button">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 col-sm-2 control-label">Emlak fotoğraf</label>
                        <div class="col-sm-10">
                            <input type="file" asp-for="Image4File" class="fileinput-button">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 col-sm-2 control-label">Emlak fotoğraf</label>
                        <div class="col-sm-8">
                            <input type="file" asp-for="Image5File" class="fileinput-button">
                        </div>
                    </div>

                </div>
                <div class="col-md-6">
                    <div class="row" id="preview1" style="padding:4px"> </div>
                    <div class="row" id="preview2" style="padding:4px"> </div>
                    <div class="row" id="preview3" style="padding:4px"> </div>
                    <div class="row" id="preview4" style="padding:4px"> </div>
                    <div class="row" id="preview5" style="padding:4px"> </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <div class="text-right">
                        <a class="btn btn-warning btn-sm" href="/Product/Userproduct">İptal</a>
                        <button type="submit" class="btn btn-primary btn-sm">Kaydet</button>
                    </div>
                </div>

            </div>
        </form>
    </div>
</section>

<script>
    $(document).ready(function () {
        $("#DisplayImageFile").change(function (e) {
            var files = e.target.files;
            $.each(files, function (i, file) {
                var reader = new FileReader();
                reader.readAsDataURL(file);
                reader.onload = function (e) {
                    var template = '<div class="col-md-6">Display Image:<div style="padding:5px"><img  height="100" width="130" src="' + e.target.result + '"/></div></div><div class="col-md-6"><div style="padding:5px"><button onclick=clearF("DisplayImageFile","preview1") class="btn btn-danger btn-xs">Remove</button></div></div>';
                    $("#preview1").append(template);
                };
            });
        });
        $("#Image2File").change(function (e) {
            var files = e.target.files;
            $.each(files, function (i, file) {
                var reader = new FileReader();
                reader.readAsDataURL(file);
                reader.onload = function (e) {
                    var template = '<div class="col-md-6">Product Image1:<div style="padding:5px"><img  height="100" width="130" src="' + e.target.result + '"/></div></div><div class="col-md-6"><div style="padding:5px"><button onclick=clearF("Image2File","preview2") class="btn btn-danger btn-xs">Remove</button></div></div>';
                    $("#preview2").append(template);
                };
            });
        });
        $("#Image3File").change(function (e) {
            var files = e.target.files;
            $.each(files, function (i, file) {
                var reader = new FileReader();
                reader.readAsDataURL(file);
                reader.onload = function (e) {
                    var template = '<div class="col-md-6">Product Image2:<div style="padding:5px"><img  height="100" width="130" src="' + e.target.result + '"/></div></div><div class="col-md-6"><div style="padding:5px"><button onclick=clearF("Image3File","preview3") class="btn btn-danger btn-xs">Remove</button></div></div>';
                    $("#preview3").append(template);
                };
            });
        });
        $("#Image4File").change(function (e) {
            var files = e.target.files;
            $.each(files, function (i, file) {
                var reader = new FileReader();
                reader.readAsDataURL(file);
                reader.onload = function (e) {
                    var template = '<div class="col-md-6">Product Image3:<div style="padding:5px"><img  height="100" width="130" src="' + e.target.result + '"/></div></div><div class="col-md-6"><div style="padding:5px"><button onclick=clearF("Image4File","preview4") class="btn btn-danger btn-xs">Remove</button></div></div>';
                    $("#preview4").append(template);
                };
            });
        });
        $("#Image5File").change(function (e) {
            var files = e.target.files;
            $.each(files, function (i, file) {
                var reader = new FileReader();
                reader.readAsDataURL(file);
                reader.onload = function (e) {
                    var template = '<div class="col-md-6">Product Image4:<div style="padding:5px"><img  height="100" width="130" src="' + e.target.result + '"/></div></div><div class="col-md-6"><div style="padding:5px"><button onclick=clearF("Image5File","preview5") class="btn btn-danger btn-xs">Remove</button></div></div>';
                    $("#preview5").append(template);
                };
            });
        });
    });
    function clearF(fieldanme, divname) {
        document.getElementById('' + fieldanme + '').value = null;
        $("#" + divname + "").empty();
    }
</script>

KEK_Emlak.Web/Views/Product/Delete.cshtml
@model KEK_Emlak.Data.Entities.Product

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<section class="wrapper">
    <h3><i class="fa fa-angle-right"></i>Emlaklarım</h3>

    <div class="form-panel">
        <h4 class="mb"><i class="fa fa-angle-right"></i>Emlak Sil</h4>
        <form class="form-horizontal style-form" method="post" asp-action="DeleteConfirm" asp-controller="Product">
            @Html.HiddenFor(m => m.Id)
            <div class="col-md-12">
                <div class="form-group">
                     @Model.Name silmek istediğinizden emin misiniz?
                </div>
                @Html.HiddenFor(s => s.AddedBy)
                @Html.HiddenFor(s => s.AddedBy)
                @Html.HiddenFor(s => s.AddedBy)
                @Html.HiddenFor(s => s.AddedBy)
                @Html.HiddenFor(s => s.AddedBy)
                @Html.HiddenFor(s => s.AddedBy)
                @Html.HiddenFor(s => s.AddedBy)
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <div class="text-right">
                        <a class="btn btn-warning btn-sm" href="/Product/UserProduct">İptal</a>
                        <button type="submit" class="btn btn-danger btn-sm">Onayla</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>

KEK_Emlak.Web/Views/Product/Details.cshtml
@model KEK_Emlak.Web.Models.ProductVM

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var returnurl = "/Product/details?id=" + Model.Id + "";
}
@*<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>


    <!DOCTYPE html>
    <html lang="en">
    <head>

        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>eCommerce Product Detail</title>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">

    </head>

    <body>*@
<form asp-action="BuyProduct" asp-controller="Buy" method="post">
    <input hidden asp-for="Id"/>
    <input hidden asp-for="Price"/>
    <div class="container">
        <div class="card">
            <div style="padding:20px">
                <div class="row">
                    <div class="col-md-6">

                        <div class="preview-pic tab-content">
                            <div class="tab-pane active" id="pic-1"><img src="@Url.Content(Model.DisplayImage)" width="430" height="258" /></div>
                            <div class="tab-pane" id="pic-2">
                                <img src="@Url.Content(Model.Image2)" width="430" height="258" />
                            </div>
                            <div class="tab-pane" id="pic-3"><img src="@Url.Content(Model.Image3)" width="430" height="258" /></div>
                            <div class="tab-pane" id="pic-4"><img src="@Url.Content(Model.Image4)" width="430" height="258" /></div>
                            <div class="tab-pane" id="pic-5"><img src="@Url.Content(Model.Image5)" width="430" height="258" /></div>
                        </div>
                        <ul class="preview-thumbnail nav nav-tabs" style="padding:10px">
                            <li class="active"><a data-target="#pic-1" data-toggle="tab"><img src="@Url.Content(Model.DisplayImage)" width="100" height="63" /></a></li>
                            <li><a data-target="#pic-2" data-toggle="tab"><img src="@Url.Content(Model.Image2)" width="100" height="63" /></a></li>
                            <li><a data-target="#pic-3" data-toggle="tab"><img src="@Url.Content(Model.Image3)" width="100" height="63" /></a></li>
                            <li><a data-target="#pic-4" data-toggle="tab"><img src="@Url.Content(Model.Image4)" width="100" height="63" /></a></li>
                            <li><a data-target="#pic-5" data-toggle="tab"><img src="@Url.Content(Model.Image5)" width="100" height="63" /></a></li>
                        </ul>

                    </div>
                    <div class="col-md-6">
                        <h3 class="text-dark">@Model.Name</h3>

                        <p class="product-description">@Model.Details</p>
                        <h5 class="price">Kategori: <span>@Model.CategoryName</span></h5>
                        <h4 class="price">Fiyat: <span>₺@Model.Price</span></h4>
                        <h4 class="price">Alan: <span>@Model.Area</span></h4>
                        <h4 class="price">Adres: <span>@Model.Location</span></h4>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (Model.canBuy == true)
                            {
                                <div class="action">
                                    <button type="submit" class="btn btn-success btn-lg">Satın Al</button>
                                </div>
                            }
                            else
                            {
                                <div class="action">
                                    <p></p>
                                </div>
                            }

                        }
                        else
                        {
                            <div class="action">
                                <a href="/Account/Login?loginurl=@returnurl" class="btn btn-success btn-lg" type="button">Almak için Giriş Yapınız</a>
                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@*</body>
    </html>*@

KEK_Emlak.Web/Views/Product/Sells.cshtml
@model IEnumerable<KEK_Emlak.Web.Controllers.SellVM>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<section class="wrapper">
    <h3><i class="fa fa-angle-right"></i> Satış Listem</h3>

    <div class="row mt">
        <div class="col-md-12">
            <div class="content-panel">
                <table class="table table-striped table-advance table-hover">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="pull-left"> <h4><i class="fa fa-angle-right"></i>Sattığım Emlaklar</h4></div>
                        </div>
                    </div>

                    <hr>
                    <thead>
                        <tr>
                            <th hidden>#</th>
                            <th>İsim</th>
                            <th>Fiyat</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td hidden>@item.SellId</td>
                                <td>@item.ProductName</td>
                                <td>@item.Price</td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
            <!-- /content-panel -->
        </div>
        <!-- /col-md-12 -->
    </div>
</section>